package cn.edu.tju.tiei.logistics.dao;

import cn.edu.tju.tiei.logistics.model.Bid;
import cn.edu.tju.tiei.logistics.model.BidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    long countByExample(BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    int deleteByExample(BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    int insert(Bid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    int insertSelective(Bid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    List<Bid> selectByExample(BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    Bid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Bid record, @Param("example") BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Bid record, @Param("example") BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bid record);
}