package cn.edu.tju.tiei.logistics.dao;

import cn.edu.tju.tiei.logistics.model.Carrier;
import cn.edu.tju.tiei.logistics.model.CarrierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarrierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    long countByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    int deleteByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    int insert(Carrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    int insertSelective(Carrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    List<Carrier> selectByExample(CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    Carrier selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Carrier record, @Param("example") CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Carrier record, @Param("example") CarrierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Carrier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrier
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Carrier record);
}