package cn.edu.tju.tiei.logistics.dao;

import cn.edu.tju.tiei.logistics.model.Waybill;
import cn.edu.tju.tiei.logistics.model.WaybillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WaybillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    long countByExample(WaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int deleteByExample(WaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int insert(Waybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int insertSelective(Waybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    List<Waybill> selectByExample(WaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    Waybill selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Waybill record, @Param("example") WaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Waybill record, @Param("example") WaybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Waybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Waybill record);
}