package cn.edu.tju.tiei.logistics.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Waybill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.loading_address
     *
     * @mbg.generated
     */
    private String loadingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.unloading_address
     *
     * @mbg.generated
     */
    private String unloadingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.freight
     *
     * @mbg.generated
     */
    private BigDecimal freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.order_time
     *
     * @mbg.generated
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.shipper_id
     *
     * @mbg.generated
     */
    private String shipperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.carrier_id
     *
     * @mbg.generated
     */
    private String carrierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table waybill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.id
     *
     * @return the value of waybill.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.id
     *
     * @param id the value for waybill.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.goods_name
     *
     * @return the value of waybill.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.goods_name
     *
     * @param goodsName the value for waybill.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.loading_address
     *
     * @return the value of waybill.loading_address
     *
     * @mbg.generated
     */
    public String getLoadingAddress() {
        return loadingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.loading_address
     *
     * @param loadingAddress the value for waybill.loading_address
     *
     * @mbg.generated
     */
    public void setLoadingAddress(String loadingAddress) {
        this.loadingAddress = loadingAddress == null ? null : loadingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.unloading_address
     *
     * @return the value of waybill.unloading_address
     *
     * @mbg.generated
     */
    public String getUnloadingAddress() {
        return unloadingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.unloading_address
     *
     * @param unloadingAddress the value for waybill.unloading_address
     *
     * @mbg.generated
     */
    public void setUnloadingAddress(String unloadingAddress) {
        this.unloadingAddress = unloadingAddress == null ? null : unloadingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.freight
     *
     * @return the value of waybill.freight
     *
     * @mbg.generated
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.freight
     *
     * @param freight the value for waybill.freight
     *
     * @mbg.generated
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.order_time
     *
     * @return the value of waybill.order_time
     *
     * @mbg.generated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.order_time
     *
     * @param orderTime the value for waybill.order_time
     *
     * @mbg.generated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.shipper_id
     *
     * @return the value of waybill.shipper_id
     *
     * @mbg.generated
     */
    public String getShipperId() {
        return shipperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.shipper_id
     *
     * @param shipperId the value for waybill.shipper_id
     *
     * @mbg.generated
     */
    public void setShipperId(String shipperId) {
        this.shipperId = shipperId == null ? null : shipperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.carrier_id
     *
     * @return the value of waybill.carrier_id
     *
     * @mbg.generated
     */
    public String getCarrierId() {
        return carrierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.carrier_id
     *
     * @param carrierId the value for waybill.carrier_id
     *
     * @mbg.generated
     */
    public void setCarrierId(String carrierId) {
        this.carrierId = carrierId == null ? null : carrierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Waybill other = (Waybill) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getLoadingAddress() == null ? other.getLoadingAddress() == null : this.getLoadingAddress().equals(other.getLoadingAddress()))
            && (this.getUnloadingAddress() == null ? other.getUnloadingAddress() == null : this.getUnloadingAddress().equals(other.getUnloadingAddress()))
            && (this.getFreight() == null ? other.getFreight() == null : this.getFreight().equals(other.getFreight()))
            && (this.getOrderTime() == null ? other.getOrderTime() == null : this.getOrderTime().equals(other.getOrderTime()))
            && (this.getShipperId() == null ? other.getShipperId() == null : this.getShipperId().equals(other.getShipperId()))
            && (this.getCarrierId() == null ? other.getCarrierId() == null : this.getCarrierId().equals(other.getCarrierId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getLoadingAddress() == null) ? 0 : getLoadingAddress().hashCode());
        result = prime * result + ((getUnloadingAddress() == null) ? 0 : getUnloadingAddress().hashCode());
        result = prime * result + ((getFreight() == null) ? 0 : getFreight().hashCode());
        result = prime * result + ((getOrderTime() == null) ? 0 : getOrderTime().hashCode());
        result = prime * result + ((getShipperId() == null) ? 0 : getShipperId().hashCode());
        result = prime * result + ((getCarrierId() == null) ? 0 : getCarrierId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", loadingAddress=").append(loadingAddress);
        sb.append(", unloadingAddress=").append(unloadingAddress);
        sb.append(", freight=").append(freight);
        sb.append(", orderTime=").append(orderTime);
        sb.append(", shipperId=").append(shipperId);
        sb.append(", carrierId=").append(carrierId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}